version: 2

default: &defaults
  working_directory: ~/angular-google-charts
  docker:
    - image: circleci/node:8-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - angular-google-charts-{{ checksum "package-lock.json" }}
            - angular-google-charts-
      - run: npm install
      - save_cache:
          key: angular-google-charts-{{ checksum "package-lock.json" }}
          paths:
             - node_modules
      - persist_to_workspace:
          root: ~/angular-google-charts
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/angular-google-charts
      - run: 
          name: Run Tests
          command: npm run ci-test
          
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/angular-google-charts
      - run:
          name: Build in production
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/angular-google-charts/dist/angular-google-charts/.npmrc
      - run:
          name: Publish package
          command: cd dist/angular-google-charts && npm publish

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires: 
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
